# Generated by Django 4.1.1 on 2022-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemeasurement',
            name='usd_price',
            field=models.DecimalField(decimal_places=19, max_digits=22),
        ),
    ]
